// confirm this data is correct

export const shipmentData = [
  {
    month: 11,
    year: 2023,
    cycle: 1,
    crystalNames: ["Dragon's Tooth Amethyst"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 2,
    crystalNames: ["Candle Quartz"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 14,
    crystalNames: ["Candle Quartz"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 3,
    crystalNames: ["Aragonite"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 13,
    crystalNames: ["Aragonite"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 4,
    crystalNames: ["Green Opal Palm Stone"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 8,
    crystalNames: ["Green Opal Palm Stone"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 5,
    crystalNames: ["Celestite"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 13,
    crystalNames: ["Celestite"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 6,
    crystalNames: ["Brazilian Quartz Clusters"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 12,
    crystalNames: ["Brazilian Quartz Clusters"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 7,
    crystalNames: ["Labradorite"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 5,
    crystalNames: ["Labradorite"],
    subscriptionShortName: "COM",
  },
  {
    month: 11,
    year: 2023,
    cycle: 8,
    crystalNames: ["Labradorite"],
    subscriptionShortName: "COM",
  },
];
