const crystalNames = [
  "Adamite",
  "Adamite (Rare)",
  "Agatised Carnelian Fossil",
  "Agni Manitite",
  "Almandine Garnet",
  "Amazonite",
  "Amethyst Cluster",
  "Amethyst Cluster Set",
  "Amethyst Globes",
  "Amethyst Lavender",
  "Amethyst Lavender Points",
  "Apache Tears",
  "Apophyllite Cluster",
  "Aragonite",
  "Arizona Azurite (Rare)",
  "Austinite",
  "Azurite",
  "Banded Agate",
  "Barite",
  "Black Kyanite",
  "Black Moonstone",
  "Black Tourmaline",
  "Black Tourmaline & Mica",
  "Bloodstone Tower",
  "Blue Calcite",
  "Blue Kyanite",
  "Blue Tara Quartz",
  "Blue Tara Quartz Set",
  "Botryoidal Chalcedony",
  "Brazilian Amethyst",
  "Brazilian Aquamarine",
  "Brazilian Kunzite",
  "Brazilian Kunzite Set",
  "Brazilian Quartz",
  "Brazilian Quartz Set",
  "Brazilian Smokey Quartz",
  "Calumet Epidote & Bassalt",
  "Canadian Emberlite",
  "Candle Quartz",
  "Caracas Druzy Quartz",
  "Carnelian Palm Stone",
  "Celestite",
  "Chabazite",
  "Chevron Amethyst",
  "Chinese Fluorite Octahedrons",
  "Chlorite Epidote Quartz",
  "Chlorite Quartz Pakistan",
  "Clay Center Celestite",
  "Clear Quartz Thomas",
  "Coated Tangerine Quartz",
  "Cobra Jasper",
  "Coconut Geode",
  "Congo Citrine",
  "Danburite",
  "Deer Creek Fire Agate",
  "Desert Roses",
  "Diopside",
  "Dragon's Tooth Amethyst",
  "Druzy Calcite",
  "Druzy Quartz",
  "Durango Apatite",
  "Elk Creek Calcite",
  "Emerald (Raw)",
  "Epidote",
  "Epidote in Matrix",
  "Etched Amethyst",
  "Faden Quartz Set",
  "Fenster Quartz",
  "Fluorite (Bigger - Non Set",
  "Fluorite and Calcite - St. Eulalia, Mexico",
  "Fluorite Set",
  "Galena",
  "Galena in Matrix",
  "Green Calcite",
  "Green Lepidolite",
  "Green Star Mica",
  "Green Tourmaline & Quartz",
  "Gypsum",
  "Hematite",
  "Hematite Picture Quartz",
  "Hematite Starbrary",
  "Hemimorphite",
  "Hiddenite",
  "Honey Calcite",
  "Hyalite Opal",
  "Iceland Spar",
  "Iceland Spar Calcite",
  "Indian Ruby",
  "Indonesian Amber",
  "Ishpeming Hematite (Rare)",
  "Jade",
  "Kabamba Jasper",
  "Kunzite Set",
  "Labradorite",
  "Lapis Lazuli",
  "Laterite Quartz",
  "Lemurian Seed",
  "Leopard Jasper",
  "Limonite Pseudomorph",
  "Lodalite Starbrary Quartz",
  "Madagascar Candle Quartz",
  "Madagascar Quartz",
  "Maharashtra Zeolite",
  "Mahrashtra Apophyllite",
  "Malachite +",
  "Mali Garnet",
  "Mexican Aragonite",
  "Mexican Green Fluorite",
  "Mexican Hemimorphite",
  "Mixed Mexican Minerals",
  "Mookaite Jasper",
  "Moroccan Amethyst",
  "Moroccan Apatite",
  "Moroccan Calcite",
  "Moroccan Carnelian",
  "Moroccan Dolomite",
  "Moroccan Fairy Stone",
  "Moroccan Garnet",
  "Moroccan Pyrite on Fluorite",
  "Moroccan Quartz & Calcite",
  "Moss Agate Tower",
  "Namibian Black Tourmaline",
  "Orange Calcite",
  "Orthoceras Fossil",
  "Othoceras Fossil",
  "Pakistani Brucite",
  "Pakistani Faden Quartz",
  "Patagonia Pink Amethyst",
  "Peach Moonstone Palm Stone",
  "Peach Selenite",
  "Peruvian Pyrite",
  "Peruvian Pyrite Cluster",
  "Pink Lemurian Set",
  "Pink Optical Calcite",
  "Pink Tourmaline Set (Raw)",
  "Polished Amethyst Tower",
  "Polished Aragonite",
  "Prehnite",
  "Purple Lepidolite Mica",
  "Pyrite in Quartz",
  "Quartz & Aurichalcite",
  "Quartz & Calcite",
  "Quebec Fairy Stone",
  "Rainbow Agate",
  "Rainbow Moonstone",
  "Red Calcite",
  "Red Feldspar",
  "Red Garnet in Matrix",
  "Red Jasper",
  "Rose Quartz",
  "Rough Labradorite",
  "Ruby",
  "Seashell Fossil",
  "Selenite Blade",
  "Selenite Cube",
  "Selenite Palm Stone",
  "Selenite Pyramind",
  "Selenite Wand",
  "Septarian",
  "Septarian Stone",
  "Shoushan Calcite",
  "Shoushan Tower",
  "Shungite",
  "Smokey Ruite Quartz",
  "Sodalite",
  "Spanish Pyrite",
  "Spinel & Dolomite",
  "Spirit Quartz",
  "Staurolite in Matrix",
  "Stromatolite",
  "Super Seven Polished",
  "Tangerine Quartz",
  "Tanzanian Green Kyanite",
  "Tiger’s Eye",
  "Tomas Gonzaga",
  "Turkish Chalcedony",
  "Ulexite",
  "Utah Shaman Stone",
  "Vanadinite",
  "Veracruz Amethyst",
  "Veracruz Amethyst Set",
  "White Feldspar",
  "Window Lepidolite",
  "Wulfenite",
  "Yellow Crazy Lace Agate",
  "Zambian Citrine",
  "Zebra Jasper",
  "Zeolite",
  "Zeolite (Non Amethyst)",
];

const crystalObjects = crystalNames.map((name) => ({ name }));

console.log(crystalObjects);
